server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.8:1111 #配置nacos地址  ngnix:负载均衡
  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud2020?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    #druid配置
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 1
        allow: 127.0.0.1
      validation-query: SELECT 1
      testWhileIdle: true
#mybatis-plus
mybatis-plus:
  global-config:
    banner: false
  type-aliases-package: cn.lhx.springcloud.entities   #别名
  configuration:
    cache-enabled: true
  mapper-locations: classpath:mapper/**/*.xml         #mapper映射文件
management:
  endpoints:
    web:
      exposure:
        include: '*'