server:
  port: 80
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率从0-1 之间   1代表全部采集
      probability: 1
#eureka
eureka:
  client:
    #表示讲自己注册进注册中心
    register-with-eureka: true
    #是否从注册中心抓取已有的注册信息，默认true，单节点无所谓，集群必须true才能配合ribbon负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7001.com:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: spring-cloud-order-80
    prefer-ip-address: true
