server:
  port: 83
spring:
  application:
    name: nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.8:8848 #配置nacos地址
#消费者将要去访问的微服务  ：注册进nacos的微服务
service-url:
  nacos-user-service: http://nacos-payment-provider