server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #注册中心
    alibaba:
      seata:
        #自定义事务组名称与seata-server中的对应
        tx-service-group: fsp_tx_group
  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/seata_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC




management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info
#mybatis-plus
mybatis-plus:
  global-config:
    banner: false
  #    别名
  type-aliases-package: cn.lhx.springcloud.domain
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl