server:
  port: 80

eureka:
  client:
    #表示讲自己注册进注册中心
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: spring-cloud-order-80
    prefer-ip-address: true

ribbon:
  #建立连接后从服务器读取可用资源所用的时间
  ReadTimeout: 5000
  #建立连接所用的时间，适用于网络正常的情况下，两端l连接所用的时间
  ConnectTimeout: 5000