server:
  port: 8401
spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    #注册中心
    sentinel:
      transport:
        dashboard: localhost:8858    #dashboard
        port: 8719
        #默认8719 占用往后+1 直至没被占用
        #clientIp: 192.168.1.8 虚拟机ip
      datasource:
        # 名称随意
        flow:
          nacos:
            server-addr: localhost:8848
            dataId: cloud-alibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'
